import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import StudentNavbar from "@/components/studentnavbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Find a job</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StudentNavbar />
      <div className="bg-blue-300 min-h-full">
        <h1>home</h1>
      </div>
    </>
  );
}
