import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import ProfileContainer from "@/components/ProfileContainer";

import StudentNavBar from "@/components/studentnavbar";
export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StudentNavBar />
      <ProfileContainer />
    </>
  );
}
